- name: install docker
  common: bash -c "curl -fsSL https://get.docker.com/ | sh"

- name: change user permission
  common: bash -c "sudo usermod -aG docker kaotu"

- name: install docker-compose
  common: bash -c "curl -L https://github.com/docker/compose/releases/download/1.25.0-rc1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose"
 
- name: change permission docker-compose
  common: bash -c "sudo chmod +x /usr/local/bin/docker-compose"
